In [14]:
import pandas as pd
df2 = pd.read_csv('survey_results_schema.csv')
df2

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [15]:
df = pd.read_csv(r'C:\Users\Iryna\Desktop\survey_results_public.csv', encoding = 'utf-8', low_memory=False) #low_memory=False - для великих обсягів даних
pd.set_option('display.max_columns', None)

list(df.columns) # ТРЕБА ВСІ НАЗВИ ПІД РУКОЮ
df

,ResponseId,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,PlatformChoice,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,PlatformHaveEntry,PlatformWantEntry,WebframeChoice,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,WebframeHaveEntry,WebframeWantEntry,DevEnvsChoice,DevEnvsHaveWorkedWith,DevEnvsWantToWorkWith,DevEnvsAdmired,DevEnvHaveEntry,DevEnvWantEntry,SOTagsHaveWorkedWith,SOTagsWantToWorkWith,SOTagsAdmired,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Cloudflare;Firebase;...,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Android Studio;Notepad++;Visual Studio;Visual ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
1,2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,Yes,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,Amazon Web Services (AWS);Datadog;Docker;Homeb...,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,Yes,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,IntelliJ IDEA;PyCharm;Visual Studio Code;Xcode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
2,3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,Yes,Datadog;Firebase;npm;pnpm,Amazon Web Services (AWS);Firebase;npm;pnpm;Vite,Firebase;npm;pnpm,NaN,NaN,Yes,Next.js;Node.js;React,Next.js;Node.js;React,Next.js;Node.js;React,NaN,Solid.js,Yes,Visual Studio Code,Visual Studio Code;Windsurf,Visual Studio Code,NaN,NaN,Google Gemini,Google Gemini;Shadcn/ui,Google Gemini,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
3,4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,Amazon Web Services (AWS);Google Cloud,NaN,NaN,Yes,Spring Boot,Spring Boot,Spring Boot,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Amazon Bedrock,NaN,NaN,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
4,5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,Yes,Amazon Web Services (AWS);APT;Docker;Make;Mave...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,Amazon Web Services (AWS);APT;Docker;Maven (bu...,NaN,NaN,Yes,Angular;ASP.NET;ASP.NET Core;Flask;jQuery,Angular;ASP.NET Core;Flask,Angular;ASP.NET Core;Flask,NaN,NaN,Yes,Eclipse;IntelliJ IDEA;Jupyter Notebook/Jupyter...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,IntelliJ IDEA;Jupyter Notebook/JupyterLab;Note...,NaN,NaN,Large Language Model;Google Gemini,Large Language Model,Large Language Model,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

In [16]:
df.iloc[:, [56,74,92,97,98,105,109,110,132,162,165]].dtypes

JobSatPoints_15_TEXT    object
DatabaseHaveEntry       object
DevEnvHaveEntry         object
SOTagsHaveEntry         object
SOTagsWant Entry        object
OfficeStackWantEntry    object
CommPlatformHaveEntr    object
CommPlatformWantEntr    object
SO_Actions_15_TEXT      object
AIAgentOrchestration    object
AIAgentObsWrite         object
dtype: object

1.1 Кількість людей, що взяла участь в опитуванні.

In [16]:
df['ResponseId'].nunique()

49191

2.1 Визначаю, скільки респондентів відповіли на всі запитання опитування

In [25]:
df2_qname = set(df2['qname']) #ПЕРЕТВОРЮЄМО QNAME НА МНОЖИНУ
df2_qname                     

df_columns = set(df.columns) #ПЕРЕТВОРЮЄМО DF КОЛОНКИ НА МНОЖИНУ
df_columns

common_questions = df2_qname.intersection(df_columns)        #ЗНАХОДИМО СПІЛЬНІ ПИТАННЯ
common_questions
df_questions_126 = df[list(common_questions)] #ЗАЛИШАЄМО ЧЕРЕЗ МАСКУ ТІЛЬКИ ПОТРІБНІ ПИТАННЯ
df_questions_126                              #КОЛОНОК 126 = ШУКАНИХ ПИТАНЬ ТЕЖ 126

,MainBranch,TechEndorse_3,Employment,AILearnHow,AIModelsHaveEntry,TechEndorse_13,AIOpen,AIThreat,JobSatPoints_1,DevEnvHaveEntry,AIAgents,LanguagesHaveEntry,JobSatPoints_11,JobSatPoints_8,ICorPM,AIAgentExternal,AIHuman,Currency,TechEndorse_2,SO_Actions_3,AgentUsesGeneral,OrgSize,SODuration,LearnCodeAI,SO_Actions_7,SO_Actions_5,JobSatPoints_10,WorkExp,LanguageChoice,AIAgentExtWrite,AIAgentOrchWrite,PlatformWantEntry,TechEndorse_13_TEXT,SO_Actions_15,JobSatPoints_9,TechEndorse_9,JobSatPoints_15,JobSat,TechOppose_3,TechOppose_13,SOAccount,AIExplain,DatabaseChoice,TechEndorse_8,OfficeStackWantEntry,SO_Actions_10,TechOppose_15,AISent,DevEnvsChoice,DatabaseHaveEntry,SOPartFreq,WebframeHaveEntry,EmploymentAddl,AIAgentObserveSecure,SO_Actions_15_TEXT,TechEndorseIntro,JobSatPoints_6,TechOppose_2,AIAgent_Uses,JobSatPoints_13,PurchaseInfluence,TechOppose_1,TechOppose_15_TEXT,YearsCode,AISelect,WebframeChoice,TechEndorse_4,AIModelsChoice,AIAgentObsWrite,OfficeStackHaveEntry,AIAgentChange,TechEndorse_5,TechOppose_11,TechOppose_16,SO_Actions_6,LearnCodeChoose,SOTagsHaveEntry,SOTagsWant Entry,JobSatPoints_2,SOVisitFreq,AIAcc,AIAgentOrchestration,SO_Dev_Content,DatabaseWantEntry,DevEnvWantEntry,JobSatPoints_16,SO_Actions_4,ToolCountPersonal,JobSatPoints_14,SO_Actions_9,JobSatPoints_5,AIAgentKnowledge,TechEndorse_6,TechEndorse_7,LanguagesWantEntry,TechOppose_9,JobSatPoints_15_TEXT,EdLevel,TechEndorse_1,CompTotal,Country,NewRole,Age,DevType,CommPlatformHaveEntr,CommPlatformWantEntr,JobSatPoints_7,SO_Actions_16,PlatformChoice,WebframeWantEntry,AIAgentKnowWrite,LearnCode,PlatformHaveEntry,Industry,ToolCountWork,AIModelsWantEntry,TechOppose_5,SOComm,JobSatPoints_4,TechOppose_7,RemoteWork,AIComplex,JobSatPoints_3,AIFrustration,SO_Actions_1,SOFriction
0,I am a developer by profession,9.0,Employed,AI CodeGen tools or AI-enabled apps,NaN,14.0,"Troubleshooting, profiling, debugging",I'm not sure,3.0,NaN,"Yes, I use AI agents at work monthly or infreq...",NaN,7.0,11.0,People manager,ChatGPT,When I don’t trust AI’s answers,EUR European Euro,7.0,6.0,NaN,20 to 99 employees,Between 5 and 10 years,"Yes, I learned how to use AI-enabled tools for...",9.0,3.0,6.0,8.0,Yes,NaN,NaN,NaN,NaN,15.0,2.0,8.0,15.0,10.0,8.0,13.0,Yes,No,Yes,1.0,NaN,11.0,16.0,Indifferent,Yes,NaN,I have never participated in Q&A on Stack Over...,NaN,"Caring for dependents (children, elderly, etc.)",NaN,NaN,Work,10.0,7.0,Software engineering,13.0,"Yes, I influenced the purchase of a substantia...",15.0,NaN,14.0,"Yes, I use AI tools monthly or infrequently",No,6.0,Yes,NaN,NaN,Not at all or minimally,3.0,6.0,3.0,7.0,"Yes, I am not new to coding but am learning ne...",NaN,NaN,1.0,A few times per week,Neither trust nor distrust,Vertex AI,NaN,NaN,NaN,8.0,2.0,3.0,14.0,8.0,5.0,NaN,11.0,12.0,NaN,1.0,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",10.0,52800.0,Ukraine,I have neither consider or transitioned into a...,25-34 years old,"Developer, mobile",NaN,NaN,12.0,NaN,Yes,NaN,NaN,Online Courses or Certification (includes all ...,NaN,Fintech,7.0,NaN,12.0,Neutral,9.0,11.0,Remote,Bad at handling complex tasks,4.0,"AI solutions that are almost right, but not quite",1.0,"Rarely, almost never"
1,I am a developer by profession,2.0,Employed,AI CodeGen tools or AI-enabled apps,NaN,14.0,All skills. AI is a flop.,I'm not sure,10.0,NaN,"No, and I don't plan to",NaN,7.0,2.0,Individual contributor,NaN,When I don’t trust AI’s answers;When I want to...,EUR European Euro,1.0,5.0,NaN,500 to 999 employees,Between 10 and 15 years,"Yes, I learned how to use AI-enabled tools for...",10.0,2.0,4.0,2.0,Yes,NaN,NaN,NaN,NaN,15.0,11.0,7.0,15.0,9.0,13.0,2.0,Not sure/can't remember,No,Yes,5.0,NaN,11.0,15.0,Indifferent,Yes,NaN,"Infrequently, less than once per year",NaN,NaN,NaN,NaN,Personal Project,1.0,1.0,NaN,13.0,No,14.0,NaN,10.0,"Yes, I use AI tools weekly",Yes,9.0,Yes,NaN,NaN,Not at all or minimally,4.0,4.0,5.0,4.0,"Yes, I am not new to coding but am learning ne...",NaN,NaN,8.0,Multiple times per day,Neither trust nor distrust,NaN,Chat (people);Message Boards;Long-form article...,NaN,NaN,5.0,8.0,5.0,14.0,9.0,12.0,NaN,3.0,12.0,NaN,3.0,NaN,"Associate degree (A.A., A.S., etc.)",13.0,90000.0,Netherlands,I have transitioned into a new career and/or i...,25-34 years old,"Developer, back-end",NaN,NaN,6.0,NaN,Yes,NaN,NaN,Online Courses or Certification (includes all ...,NaN,Retail and Consumer Services,6.0,NaN,10.0,"Yes, somewhat",9.0,9.0,"Hybrid (some in-person, leans heavy to flexibi...",Bad at handling complex tasks,3.0,"AI solutions that are almost right, but not qu...",6.0,About half of the time
2,I am a developer by profession,3.0,"Independent contractor, freelancer, or self-em...",AI CodeGen tools or AI-enabled apps;Technical ...,NaN,14.0,"Understand how things actually work, problem s...",No,9.0,NaN,"Yes, I use AI agents at work weekly",NaN,3.0,5.0,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,When I don’t trust AI’s answers;When I want to...,UAH Ukrainian hryvnia,2.0,4.0,Multi-platform search enablement,NaN,Between 5 and 10 years,"Yes, I learned how to use AI-enabled tools for...",9.0,1.0,4.0,10.0,Yes,NaN,NaN,NaN,NaN,15.0,2.0,4.0,15.0,8.0,2.0,4.0,Not sure/can't remember,No,Yes,1.0,NaN,11.0,15.0,Favorable,Yes,NaN,"Infrequently, less than once per year",NaN,None of the above,NaN,NaN,Work,12.0,1.0,Software engineering,13.0,No,8.0,NaN,12.0,"Yes, I use AI tools daily",Yes,7.0,Yes,NaN,NaN,"Yes, somewhat",5.0,9.0,11.0,2.0,"Yes, I am not new to coding but am learning ne...",NaN,NaN,6.0,A few times per week,Somewhat trust,NaN,Chat (people);Videos;Lists of recommendations ...,NaN,NaN,10.0,5.0,3.0,14.0,7.0,8.0,Redis,10.0,13.0,NaN,3.0,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",12.0,2214000.0,Ukraine,I have transitioned into a new career and/or i...,35-44 years old,"Developer, front-end",NaN,NaN,1.0,NaN,Yes,Solid.js,NaN,Online Courses or Certification (includes all ...,NaN,Software Development,3.0,NaN,12.0,Neutral,11.0,13.0,NaN,Neither good or bad at handling complex tasks,7.0,"AI solutions that are almost right, but not qu...",3.0,About half of the time
3,I am a developer by profession,6.0,Employed,AI CodeGen tools or AI-enabled apps;Videos (no...,NaN,14.0,NaN,No,1.0,NaN,"Yes, I use AI agents at work monthly or infreq...",NaN,12.0,9.0,Individual contributor,ChatGPT;Claude Code,When I don’t trust AI’s answers;When I want to...,EUR European Euro,12.0,4.0,Language processing,"10,000 or more employees",Between 3 and 5 years,"Yes, I learned how to use AI-enabled tools for...",9.0,6.0,11.0,4.0,Yes,NaN,NaN,NaN,NaN,15.0,10.0,7.0,15.0,6.0,8.0,7.0,Yes,NO,No,11.0,NaN,11.0,15.0,Favorable,No,NaN,I have never participated in Q&A on Stack Over...,NaN,None of the above,NaN,NaN,Personal Project,7.0,5.0,Software engineering,13.0,No,10.0,NaN,5.0,"Yes, I use AI tools weekly",Yes,5.0,No,NaN,NaN,Not at all or minimally,13.0,2.0,1.0,7.0,"Yes, I am not new to coding but am learning ne...",NaN,NaN,2.0,A few times per month or weekly,Somewhat trust,NaN,Videos;Chat (bot/AI),NaN,NaN,3.0,5.0,NaN,14.0,8.0,6.0,NaN,3.0,8.0,NaN,12.0,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",2.0,31200.0,Ukraine,I have neither consider or transitioned into a...,35-44 years old,"Developer, back-end",NaN,NaN,8.0,NaN,Yes,NaN,NaN,"Other online resources (e.g. standard search, ...",NaN,Retail and Consumer Services,NaN,NaN,4.0,Neutral,5.0,13.0,Remote,Bad at handling complex tasks,4.0,"AI solutions that are almost right, but not qu...",1.0,"Rarely, almost never"
4,I am a developer by profession,1.0,"Independent contractor, freelancer, or self-em...",Technical documentation (is generated for/by t...,NaN,14.0,"critical thinking, the skill to define the tas...",No,9.0,NaN,"No, and I don't plan to",NaN,1.0,5.0,NaN,NaN,When I don’t trust AI’s answers,USD United States dollar,3.0,7.0,NaN,NaN,Between 5 and 10 years,"Yes, I learned how to use AI-enabled tools for...",6.0,2.0,2.0,21.0,Yes,NaN,NaN,NaN,NaN,15.0,7.0,2.0,15.0,7.0,3.0,8.0,No,partly,Yes,4.0,NaN,12.0,15.0,Favorable,Yes,NaN,"Infrequently, less than once per year",NaN,"Caring for dependents (children, elderly, etc.)",NaN,NaN,Work,8.0,13.0,NaN,12.0,"Yes, I endorsed a tool that was open-source an...",7.0,NaN,22.0,"Yes, I use AI tools weekly",Yes,9.0,Yes,NaN,NaN,"Yes, to a great extent",10.0,1.0,14.0,5.0,"No, I am not new to coding and did not learn n...",NaN,NaN,4.0,A few times per month or weekly,Neither trust nor distrust,NaN,Long-form articles,NaN,NaN,3.0,4.0,3.0,10.0,10.0,14.0,NaN,8.0,7.0,NaN,6.0,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",6.0,60000.0,Ukraine,I have neither consider or transitioned into a...,35-44 years old,Engineering manager,NaN,NaN,6.0,NaN,Yes,NaN,NaN,NaN,NaN,Software Development,4.0,NaN,9.0,"No, not really",13.0,12.0,NaN,"Good, but not great at handling complex tasks",11.0,"AI solutions that are almost right, but not quite",1.0,"Rarely, almost never"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,I code primarily as a hobby,NaN,Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",NaN,NaN,NaN,NaN,18-24 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,I am a developer by profession,NaN,Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Caring for dependents (children, elderly, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some college/university study without earning ...,NaN,NaN,NaN,NaN,45-54 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Online Courses or Certification (includes all ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,1.0,Employed,AI CodeGen tools or AI-enabled apps;Videos (no...,NaN,10.0,NaN,No,3.0,NaN,"No, I use AI exclusively in copilot/autocomple...",NaN,8.0,10.0,People manager,NaN,NaN,EUR European Euro,2.0,NaN,NaN,"10,000 or more employees",NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,5.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,6.0,15.0,9.0,2.0,3.0,NaN,"Yes, partially.",NaN,4.0,NaN,NaN,10.0,Favorable,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,Personal Project,9.0,6.0,NaN,11.0,"Yes, I endorsed a tool that was open-source an...",9.0,NaN,31.0,"Yes, I use AI tools monthly or infrequently",NaN,5.0,NaN,NaN,NaN,Not at all or minimally,3.0,1.0,8.0,NaN,"Yes, I am not new to coding but am learning ne...",NaN,NaN,6.0,NaN,Neither trust nor distrust,NaN,NaN,NaN,NaN,14.0,NaN,35.0,12.0,NaN,4.0,NaN,7.0,8.0,NaN,4.0,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",9.0,80000.0,Italy,I have somewhat considered changing my career ...,35-44 years old,"Architect, software or solutions",NaN,NaN,1.0,NaN,NaN,NaN,NaN,Online Courses or Certification (includes all ...,NaN,Banking/Financial Services,25.0,NaN,7.0,NaN,13.0,5.0,"Hybrid (some in-person, leans heavy to flexibi...","Good, but not great at handling complex tasks",7.0,"AI solutions that are almost right, but not qu...",NaN,NaN
49189,I am a developer by profession,NaN,"Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None of the above,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",NaN,NaN,NaN,NaN,25-34 years old,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Videos (not associated with specific online co...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,"I am not primarily a developer, but I write co...",NaN,Student,AI CodeGen tools or AI-enabled apps,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Attending school (full-time),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I am not new to coding but am learning ne...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Some college/university study without earning ...,NaN,NaN,NaN,NaN,18-24 years old,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Online Courses or Certification (includes all ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
answ_all_quest = df_questions_126.notna().all(axis=1) #Якщо всі значення в рядку True = людина відповіла на всі питання
answ_all_quest.sum()                                      #РАХУЄМО ТИХ, ХТО ВІДПОВІВ НА ВСЕ
                                                          #ЖОДНА ЛЮДИНА НЕ ВІДПОВІЛА НА ВСЕ

np.int64(0)

In [34]:
df_questions_126.isna().sum(axis=1).min() #ПЕРЕВІРКА, ЧИ СПРАВЖНЄ ТВЕРДЖЕННЯ ВИЩЕ

4

3.1 Обчисли міри центральної тенденції для поля WorkExp (досвід роботи респондентів):
Середнє значення (mean)
Медіану (median)
Моду (mode)

In [39]:
df['WorkExp'].dtype #ПЕРЕВІРЯЄМО ТИП КОЛОНКИ
df['WorkExp'].isna().sum() #np.int64(6298)
df['WorkExp'].unique() #ПЕРЕВІРИЛА НА ТЕКСТ - Є ОДИН ЗАПИС  - 'nan'

np.int64(6298)

ШУКАЄМО СЕРЕДНЄ, МОДУ ТА МЕДІАНУ

In [46]:

df['WorkExp'].mean()

np.float64(13.367402606485907)

In [47]:
df['WorkExp'].median()

10.0

In [48]:
df['WorkExp'].mode()[0]

np.float64(10.0)

In [45]:
df['WorkExp'].isna().mean() * 100 #ВІДСОТОК ПРОПУСКІВ У КОЛОНЦІ - 12.8%
  #МОЖНА НИМ ЗНЕХТУВАТИ І НІЧОГО НЕ РОБИТИ

np.float64(12.803155048687767)

4. Визнач кількість респондентів, які працюють віддалено (remote).

Стовпчик із питаннями про віддалену чи не віддалену роботу = RemoteWork

In [54]:
df['RemoteWork'].value_counts() #ДИВИМОСЬ, ЩО ВЗАГАЛІ ПИШУТЬ НА ЦЕ ПИТАННЯ

RemoteWork
Remote                                                                          10931
Hybrid (some remote, leans heavy to in-person)                                   6732
In-person                                                                        6042
Hybrid (some in-person, leans heavy to flexibility)                              5831
Your choice (very flexible, you can come in when you want or just as needed)     4244
Name: count, dtype: int64

In [59]:
(df['RemoteWork'] == 'Remote').sum() #ОТЖЕБ 10 931 ПРАЦЮЮТЬ ВІДДАЛЕНО

np.int64(10931)

5. Обчислюю відсоток респондентів, які програмують на Python

In [79]:
df.columns[df.columns.str.contains('Language', case=False)] #ТАКИМ СПОСОБОМ ЗНАХОДИМО КОЛОНКУ ІЗ МОВАМИ
                                                            #НА ЯКИХ ПРОГРАМУВАЛА ЛЮДИНА. ЦЕ - 'LanguageHaveWorkedWith'
df['LanguageHaveWorkedWith'].value_counts().reset_index() #дивлюсь, що у ній є
df['LanguageHaveWorkedWith'].head()

0                     Bash/Shell (all shells);Dart;SQL
1                                                 Java
2                  Dart;HTML/CSS;JavaScript;TypeScript
3                                      Java;Kotlin;SQL
4    C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
Name: LanguageHaveWorkedWith, dtype: object

In [167]:
python_users = df['LanguageHaveWorkedWith'].str.contains('Python', na=False)  #ШУКАЮ ЛЮДЕЙ З PYTHON

python_users_perc = python_users.mean() * 100

print(f"python_users_perc: {percentage:.1f}%")

python_users_perc: 37.5%

6. Визначаю, скільки респондентів навчалося програмувати за допомогою онлайн курсів. Відповідний стовпчик - 'LearnCode'

In [162]:
df['LearnCode'].dtype  #ТАК САМО ШУКАЮ ОНЛАЙН КУРСИ
onl_cours_learn = df['LearnCode'].str.contains('Online Courses', na=False).sum()

onl_cours_learn

np.int64(10973)

In [163]:
onl_courses_perc = (total_onl_courses/total_users) *100   
onl_courses_perc        #ВІДСОТОК СЕРЕД ВСІХ - 22%

np.float64(22.30692606371084)

7. Серед респондентів, що програмують на Python, проводжу аналіз компенсації (ConvertedCompYearly) в розрізі країн. Для кожної країни обчисли:
Середню суму компенсації
Медіанну суму компенсації

In [182]:
python_df = df[python_users] #ФІЛЬТРУЮ ДАТАСЕТ, ЩОБ БУЛИ ТІЛЬКИ ТІ, ХТО ПРАЦЮЮТЬ НА ПАЙТОН
                            
python_df['ConvertedCompYearly'].isna().sum() # ДИВИМОСЬ ПРОПУСКИ
python_df = python_df.dropna(subset=['ConvertedCompYearly']) #ВИДАЛЯЄМО ТИХ, ХТО БЕЗ КОМПЕНСАЦІЇ
yearly_comp_by_country = python_df.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median']).reset_index().round() #ГРУПУЄМО, АГРЕГУЄМО, РАХУЄМО,ОКРУГЛЮЄМО
yearly_comp_by_country

                                  Country      mean    median
0                             Afghanistan   22329.0    1000.0
1                                 Albania   47218.0   50000.0
2                                 Algeria   20187.0    7088.0
3                                 Andorra  226104.0  226104.0
4                     Antigua and Barbuda       1.0       1.0
..                                    ...       ...       ...
148  Venezuela, Bolivarian Republic of...    9909.0    3000.0
149                              Viet Nam  218837.0    8254.0
150                                 Yemen   32930.0   23672.0
151                                Zambia    5424.0    3206.0
152                              Zimbabwe   34000.0   25500.0

[153 rows x 3 columns]

8. Знайти топ-5 людей з найбільшою компенсацією та подивитись, яка в них освіта. Рівень освіти = 'EdLevel'

In [193]:
python_top5_most_paid = python_df[['EdLevel', 'ConvertedCompYearly']].sort_values(by='ConvertedCompYearly', ascending=False).head(5)
python_top5_most_paid
#СУДЯЧИ З РІЗНОМАНІТНОСТІ ОСВІТИ, УСПІХ ПАЙТОН-ЮЗЕРА ВІД НЕЇ НЕ ЗАЛЕЖИТЬ АБ-СО-ЛЮ-ТНО

                                                 EdLevel  ConvertedCompYearly
48428       Bachelor’s degree (B.A., B.S., B.Eng., etc.)           10000000.0
30728     Professional degree (JD, MD, Ph.D, Ed.D, etc.)            6371285.0
40418  Some college/university study without earning ...            6000000.0
19536     Professional degree (JD, MD, Ph.D, Ed.D, etc.)            5810837.0
14873  Secondary school (e.g. American high school, G...            4706124.0